---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetex
  namespace: default
  labels:
    app.kubernetes.io/name: kubernetex
    app.kubernetes.io/instance: kubernetex-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetex
      app.kubernetes.io/instance: kubernetex-node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubernetex
        app.kubernetes.io/instance: kubernetex-node
    spec:
      containers:
        - name: main
          image: bezerrajs/kubernetex:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RELEASE_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: RELEASE_COOKIE
              valueFrom:
                secretKeyRef:
                  name: kubernetex-cluster
                  key: ERLANG_COOKIE
          ports:
            - name: epmd
              containerPort: 4369
              protocol: TCP